######################################################################
# Automatically generated by qmake (3.0) ?? 12? 28 08:47:46 2016
######################################################################

QT       += core gui  multimedia multimediawidgets network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = Camera
TEMPLATE = app


SOURCES += main.cpp\
        mainwindow.cpp

HEADERS  += mainwindow.h

FORMS    += mainwindow.ui
